let wind = false;
let log = true;
let xWindStrength = 0.3;
let zWindStrength = 0.3;
let yWindStrength = 0.3;
let shapePosition = new THREE.Vector3(0,0,0)
let sphereRadius = 0.5
let GRAVITY_STRENGTH = 4;
let TIME_STEP = 1/140
let OBJECT_SPEED = 2
let DRAG = 0.1
